### ISSUE TITLE
rename task name

### ISSUE THREAD

**Issue by toptalo** [yiminghe/grunt-class-id-minifier#2]
Hello!
Current task name (class-id-minifier) is invalid for javascript object param name.

Grunt returns error 'Unexpected token "-"'

I see two ways to fix it:
1 (bad way) - edit readme file ad get class-id-minifier in quotes like this:

```javascript
grunt.initConfig({
    'class-id-minifier': {
        options: {
          // Task-specific options go here.
        },
        your_target: {
          // Target-specific file lists and/or options go here.
        },
      },
})
``` 

2 - rename task name to something else

**Comment by yiminghe** [comment]
quote is fine
